/*
* Generated by codegen on {{ data.generation_time }}
* Catalog: {{data.table_catalog}}
* Relation: {{data.table.table_schema}}.{{data.table.table_name}}
*/
{% set HEADER_GUARD="MODEL_MAPPING_%s_%s_HXX" % (data.table.table_schema.upper(), data.table.table_name.upper()) %}
#ifndef {{ HEADER_GUARD }}
#define {{ HEADER_GUARD }}

#include <nix/core/types/serializable.hxx>
#include <nix/util/types.hxx>
#include <nix/db/types/array.hxx>

#define SOCI_USE_BOOST
#include <boost/tuple/tuple.hpp>
#include <soci/soci.h>
#include <boost/optional.hpp>
#include <nix/common.hxx>
#include <string>
#include <ctime>


namespace mapping {
namespace {{data.table.table_schema}} {

{% block class_def %}
{% endblock class_def %}

} // {{data.table.table_schema}}
} // mapping

namespace soci {

{% block type_conversion_def %}
{% endblock type_conversion_def %}

} // soci

#endif // {{ HEADER_GUARD }}
